-- USE DATABASE ACTIVIDAD_1_1
-- GO
CREATE TABLE PAISES(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    Nombre VARCHAR(100)
)
CREATE TABLE LOCALIDADES(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    IdPais INT NOT NULL FOREIGN KEY REFERENCES PAISES(ID)
)
CREATE TABLE USUARIOS(
    ID INT PRIMARY KEY IDENTITY (1,1),
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    FechaDeNacimiento DATE NOT NULL,
    Usuario VARCHAR(50) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Genero BIT NOT NULL,
    Telefono INT NULL,
    Celular INT NULL,
    IdLocalidad INT NOT NULL FOREIGN KEY REFERENCES LOCALIDADES(ID)
)
CREATE TABLE INSCRIPCIONES(
    ID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
    IdCurso INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID),
    IdUsuario INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
    FechaInscripcion DATE NOT NULL
)
CREATE TABLE CERTIFICACIONES(
    IdInscripcion INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES INSCRIPCIONES(ID),
    Fecha DATE NOT NULL,
    Costo MONEY NOT NULL
)
CREATE TABLE PAGOS(
    ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    IdInscripcion INT NOT NULL FOREIGN KEY REFERENCES INSCRIPCIONES(ID),
    Fecha DATE NOT NULL,
    Importe MONEY NOT NULL
)
CREATE TABLE RESENIAS(
    IdInscripcion INT NOT NULL PRIMARY KEY FOREIGN KEY REFERENCES INSCRIPCIONES(ID),
    Fecha DATE NOT NULL,
    Observacion VARCHAR(500) NOT NULL,
    Puntaje DECIMAL(3,1) NOT NULL
)
CREATE TABLE INSTRUCTORES_POR_CURSO(
    IdUsuario INT NOT NULL FOREIGN KEY REFERENCES USUARIOS(ID),
    IdCurso INT NOT NULL FOREIGN KEY REFERENCES CURSOS(ID),
    PRIMARY KEY(IdUsuario,IdCurso)
)
