create DATABASE TP_1A
GO
use TP_1A
GO
-- TABLAS GEOGRAFICAS
CREATE TABLE Provincias(
    ID SMALLINT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
)
CREATE TABLE Localidades(
    ID SMALLINT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    IDProvincia SMALLINT NOT NULL FOREIGN KEY REFERENCES Provincias(ID)  
)
CREATE TABLE CodigosPostales(
    ID SMALLINT NOT NULL PRIMARY KEY,
    IDLocalidad SMALLINT NOT NULL FOREIGN KEY REFERENCES Localidades(ID)
)
CREATE TABLE Direccion(
    ID SMALLINT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL,
    IDCodigoPostal SMALLINT NOT NULL FOREIGN KEY REFERENCES CodigosPostales(ID)
)
-- TABLAS DE OPCIONES
CREATE TABLE Generos(
    ID CHAR NOT NULL PRIMARY KEY,
    Nombre  VARCHAR(30)
)
CREATE TABLE MetodosDePagos(
    ID CHAR NOT NULL PRIMARY KEY,
    Nombre VARCHAR(30)
)
CREATE TABLE TiposDeArticulos(
    ID SMALLINT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL
)
CREATE TABLE Marcas(
    Nombre VARCHAR (50) NOT NULL PRIMARY KEY
)
--TABLAS PRINCIPALES
CREATE TABLE Articulos(
    ID VARCHAR(30) NOT NULL PRIMARY KEY,
    Descripcion VARCHAR(100) NULL,
    Marca VARCHAR(50) NULL FOREIGN KEY REFERENCES Marcas(Nombre),
    PrecioCompra SMALLMONEY NULL,
    PrecioVenta SMALLMONEY NULL,
    IDTipoArticulo SMALLINT NULL FOREIGN KEY REFERENCES TiposDeArticulos(ID),
    StockMinimo SMALLINT NULL,
    Stock SMALLINT NOT NULL CHECK (Stock >= 0),
    Estado BIT DEFAULT 1 NOT NULL
)
--TABLAS PRINCIPALES
CREATE TABLE Clientes(
    DNI INT NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Sexo CHAR NULL FOREIGN KEY REFERENCES Generos(ID),
    Telefono INT NOT NULL UNIQUE,
    Mail VARCHAR(80) NOT NULL UNIQUE,
    FechaAltaSistema DATE NOT NULL,
    FechaNacimiento DATE NOT NULL,
    IDDireccion SMALLINT NOT NULL FOREIGN KEY REFERENCES Direccion(ID)
)
CREATE TABLE Vendedores(
    DNI INT NOT NULL PRIMARY KEY,
    Legajo INT UNIQUE,
    Nombre VARCHAR(50),
    Apellido VARCHAR(50),
    Sexo CHAR NULL FOREIGN KEY REFERENCES Generos(ID),
    Telefono INT NOT NULL UNIQUE,
    FechaNacimiento DATE NOT NULL,
    FechaIngreso DATE NOT NULL,
    IDDireccion SMALLINT NOT NULL FOREIGN KEY REFERENCES Direccion(ID),
    Sueldo MONEY NOT NULL CHECK (Sueldo > 0)
)
CREATE TABLE Ventas(
    CodigoFactura INT NOT NULL PRIMARY KEY,
    Fecha DATE NOT NULL,
    DNICliente INT NOT NULL FOREIGN KEY REFERENCES Clientes(DNI),
    DNIVendedor INT NOT NULL FOREIGN KEY REFERENCES Vendedores(DNI),
    MetodoDePago CHAR NOT NULL FOREIGN KEY REFERENCES MetodosDePagos(ID),
    ImporteTotal MONEY NOT NULL CHECK(ImporteTotal > 0)
)
CREATE TABLE ArticulosPorVenta(
    CodigoFactura INT NOT NULL FOREIGN KEY REFERENCES Ventas(CodigoFactura),
    IDArticulo VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Articulos(ID),
    Cantidad SMALLINT NOT NULL,
    PRIMARY KEY(CodigoFactura, IDArticulo)
)


